version: "3.9"

services:
  laravel:
    container_name: laravel
    image: bitnami/laravel:latest
    volumes:
      - ./<source-path>/:/app/
    command: bash -c "composer update && php artisan serve --host=0.0.0.0 --port=8000"
